services:
  jenkins:
    image: custom-jenkins/jenkins:jdk21
    build:
      dockerfile: Dockerfile
      context: .
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    networks:
      - network-jenkins
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      TZ: Asia/Bangkok
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home

networks:
  network-jenkins:
    name: network-jenkins
    driver: bridge
